// event.rs — repository functions for the Event entity.
//
// The storage layer's interface for Events. It exposes:
//   • insert_event                  — write a new event
//   • fetch_event                   — read one event by id
//   • list_events                   — read all events, ordered by start time
//   • update_event                  — update a native event's mutable fields
//   • upsert_external_events        — insert-or-update ICS-ingested events,
//                                      keyed on (calendar_id, external_id)
//   • prune_events_missing_from_feed — delete a calendar's events (and their
//                                      instances) that vanished from its feed
//
// No business logic lives here; the repository reads and writes the `Event`
// domain type. See migrations 0003 and 0004.
//
// Storage layout notes:
//   • The EventSource is flattened onto the events row as `source_*` columns
//     rather than a separate table — a source is 1:1 with its event and never
//     queried on its own. `row_to_event` reassembles it.
//   • Recurrence is stored as two nullable columns (rrule + timezone), both
//     present or both NULL, like tasks (ADR-0002); a half-set pair is a data bug.
//   • Booleans (`all_day`, `source_read_only`) are INTEGER 0/1 under STRICT mode.
//   • Datetimes are RFC 3339 TEXT with an explicit offset, so `ORDER BY` on a
//     time column is a correct chronological sort without a parse step.
//   • The SELECT column list lives in one const (`EVENT_SELECT`); the fetch and
//     list queries append their own WHERE / ORDER BY, so it is never duplicated.
//   • `insert_event`, `update_event`, and `upsert_external_events` share the
//     transformed-field serialisation (all the columns that need parsing, not
//     just borrowing) via the private `event_columns` helper, so the three
//     write paths cannot drift on how a bool/enum/datetime is encoded.

// `SqlitePool` is the shared pool injected into every query function.
use sqlx::SqlitePool;
// `OffsetDateTime` is the canonical timestamp type; RFC 3339 is the storage form.
use time::OffsetDateTime;
// The RFC 3339 format descriptor used for both serialisation and deserialisation.
use time::format_description::well_known::Rfc3339;

// Domain types this module reads/writes.
use amity_core::event::{Event, EventSource, EventSourceKind};
use amity_core::ids::EventId;
use amity_core::recurrence::RecurrenceRule;

// `StorageError` wraps sqlx errors and field-parse failures.
use crate::StorageError;

// ─── Row type ────────────────────────────────────────────────────────────────

/// Raw database row from the `events` table.
///
/// Every field is `String`/`Option<String>`/`i64` because the database stores
/// everything as TEXT or INTEGER — there are no typed datetime, bool, or UUID
/// columns to lean on. Conversion to the domain type (parsing UUIDs, datetimes,
/// the recurrence pair, and the flattened source) happens in `row_to_event`.
/// Field names must match the SQL columns exactly for `sqlx::FromRow` to map
/// them without a `#[sqlx(rename = "…")]` annotation.
#[derive(sqlx::FromRow)]
struct EventRow {
    // UUID TEXT — the event's primary key.
    id: String,
    // One-line title.
    title: String,
    // RFC 3339 TEXT start instant.
    start_at: String,
    // RFC 3339 TEXT end instant, or NULL.
    end_at: Option<String>,
    // 0/1 all-day flag.
    all_day: i64,
    // IANA timezone name.
    timezone: String,
    // Optional free-form location.
    location: Option<String>,
    // RRULE string, or NULL for one-shot/external events.
    recurrence_rrule: Option<String>,
    // IANA timezone for recurrence; NULL iff recurrence_rrule NULL.
    recurrence_timezone: Option<String>,
    // 'native' | 'ics'.
    source_kind: String,
    // External id, or NULL for native.
    source_external_id: Option<String>,
    // External calendar id, or NULL for native.
    source_calendar_id: Option<String>,
    // 0/1 read-only flag.
    source_read_only: i64,
    // RFC 3339 TEXT last-sync time, or NULL.
    source_last_synced_at: Option<String>,
    // RFC 3339 TEXT creation timestamp.
    created_at: String,
    // RFC 3339 TEXT last-modification timestamp.
    updated_at: String,
}

// ─── Public repository functions ─────────────────────────────────────────────

/// Insert a new event.
///
/// All fields come from the `Event` struct; ids and timestamps are generated by
/// the domain layer (`EventBuilder::build`), so this function neither reads the
/// clock nor generates ids. The 16-column INSERT mirrors the `events` table from
/// migration 0003, with the source flattened onto the `source_*` columns. If new
/// columns are added later, this INSERT and `update_event` must both be updated.
///
/// # Errors
///
/// Returns `StorageError::Database` on any sqlx failure (e.g. a UUID primary-key
/// or FK violation), or `StorageError::Parse` if a timestamp cannot be formatted.
pub async fn insert_event(pool: &SqlitePool, event: &Event) -> Result<(), StorageError> {
    // UUID newtype → hyphenated string.
    let id = event.id.to_string();
    // Every transformed field (bools/enums/datetimes) comes from the shared
    // helper so insert/update/upsert cannot drift on how one is encoded.
    let cols = event_columns(event)?;
    // Audit timestamps → RFC 3339 TEXT. Both start equal at insert time.
    let created_at = format_dt(event.created_at)?;
    let updated_at = format_dt(event.updated_at)?;

    // Write the row; the binds below fill ?1..?16 in the column order above.
    sqlx::query(
        "
        INSERT INTO events (
            id, title, start_at, end_at, all_day, timezone, location,
            recurrence_rrule, recurrence_timezone,
            source_kind, source_external_id, source_calendar_id,
            source_read_only, source_last_synced_at,
            created_at, updated_at
        ) VALUES (
            ?1, ?2, ?3, ?4, ?5, ?6, ?7,
            ?8, ?9,
            ?10, ?11, ?12,
            ?13, ?14,
            ?15, ?16
        )
        ",
    )
    // Bind in the same order as the ?1..?16 placeholders above; each parameter
    // maps to exactly one column of the events row.
    // ?1 primary key.
    .bind(id)
    // ?2 title (already validated non-empty by the domain layer).
    .bind(&event.title)
    // ?3 start instant.
    .bind(cols.start_at)
    // ?4 end instant, or SQL NULL.
    .bind(cols.end_at)
    // ?5 all-day flag as 0/1.
    .bind(cols.all_day)
    // ?6 IANA timezone.
    .bind(&event.timezone)
    // ?7 location, or SQL NULL.
    .bind(&event.location)
    // ?8/?9 recurrence rrule + timezone, both NULL for one-shot/external.
    .bind(cols.recurrence_rrule)
    .bind(cols.recurrence_timezone)
    // ?10 source kind ('native' | 'ics').
    .bind(cols.source_kind)
    // ?11/?12 external id + calendar id, NULL for native.
    .bind(&event.source.external_id)
    .bind(&event.source.calendar_id)
    // ?13 read-only flag as 0/1.
    .bind(cols.source_read_only)
    // ?14 last-sync time, NULL for native.
    .bind(cols.source_last_synced_at)
    // ?15/?16 audit timestamps.
    .bind(created_at)
    .bind(updated_at)
    .execute(pool)
    .await?;

    Ok(())
}

/// Fetch a single event by id.
///
/// Returns `None` when no event has that id — a non-exceptional "not found"
/// that the caller maps to a 404 (or ignores) as it sees fit. When a row exists
/// it is parsed back into a full `Event` via `row_to_event`.
///
/// # Errors
///
/// Returns `StorageError::Database` on sqlx failure, or `StorageError::Parse` if
/// a stored value cannot be decoded.
pub async fn fetch_event(pool: &SqlitePool, id: EventId) -> Result<Option<Event>, StorageError> {
    // The typed id becomes a hyphenated UUID string for the bind parameter.
    let id_str = id.to_string();

    // Append the WHERE clause to the shared column list.
    let sql = format!("{EVENT_SELECT} WHERE id = ?1");
    // `fetch_optional` yields None when no row matches.
    // Run the parameterised select and map at most one row.
    let row: Option<EventRow> = sqlx::query_as(&sql)
        .bind(id_str)
        .fetch_optional(pool)
        .await?;

    // Parse only when a row exists.
    match row {
        Some(r) => Ok(Some(row_to_event(r)?)),
        None => Ok(None),
    }
}

/// List all events, ordered by `start_at` ascending.
///
/// The surfacing layer loads the full set and filters to the target day in the
/// service; at household scale the event count is small enough not to need a
/// windowed query here, and keeping the filtering in one place (the pure rule)
/// is worth the small over-fetch. A dated-window variant can be added later if
/// the event count ever grows large enough to matter.
///
/// # Errors
///
/// Returns `StorageError::Database` on sqlx failure, or `StorageError::Parse` if
/// a stored row cannot be decoded.
pub async fn list_events(pool: &SqlitePool) -> Result<Vec<Event>, StorageError> {
    // Order by start time so callers get a chronological list by default.
    let sql = format!("{EVENT_SELECT} ORDER BY start_at ASC");
    // Fetch every row, then parse each into a domain Event.
    let rows: Vec<EventRow> = sqlx::query_as(&sql).fetch_all(pool).await?;

    // Parse each row; stop at the first error rather than skipping corrupt rows.
    rows.into_iter().map(row_to_event).collect()
}

/// Update a native event's mutable fields and bump `updated_at`.
///
/// Updates every mutable column from the supplied `Event` (identified by `id`)
/// in one statement, so the caller sends a whole struct rather than a diff;
/// `created_at` is the only immutable field. The service layer sets `updated_at`
/// before calling — this module never reads the clock. If the recurrence rule
/// changed, deleting old future instances and re-materialising from the new rule
/// is the caller's responsibility (see `event_instance`), not this function's.
///
/// # Errors
///
/// Returns `StorageError::Database` on sqlx failure, or `StorageError::Parse` if
/// a timestamp cannot be formatted.
pub async fn update_event(pool: &SqlitePool, event: &Event) -> Result<(), StorageError> {
    // The id goes in the WHERE clause, not the SET list.
    let id = event.id.to_string();
    // Shared transformed-field serialisation (see insert_event).
    let cols = event_columns(event)?;
    // updated_at is bumped by the caller before this runs.
    let updated_at = format_dt(event.updated_at)?;

    // Update every mutable column in one statement, keyed by id in the WHERE.
    sqlx::query(
        "
        UPDATE events
        SET    title = ?1, start_at = ?2, end_at = ?3, all_day = ?4,
               timezone = ?5, location = ?6,
               recurrence_rrule = ?7, recurrence_timezone = ?8,
               source_kind = ?9, source_external_id = ?10, source_calendar_id = ?11,
               source_read_only = ?12, source_last_synced_at = ?13,
               updated_at = ?14
        WHERE  id = ?15
        ",
    )
    // Bind in the same order as ?1..?14 in SET, then ?15 for the WHERE id.
    // ?1 title.
    .bind(&event.title)
    // ?2 start instant.
    .bind(cols.start_at)
    // ?3 end instant, or NULL.
    .bind(cols.end_at)
    // ?4 all-day flag.
    .bind(cols.all_day)
    // ?5 timezone.
    .bind(&event.timezone)
    // ?6 location, or NULL.
    .bind(&event.location)
    // ?7/?8 recurrence rrule + timezone.
    .bind(cols.recurrence_rrule)
    .bind(cols.recurrence_timezone)
    // ?9 source kind.
    .bind(cols.source_kind)
    // ?10/?11 external id + calendar id.
    .bind(&event.source.external_id)
    .bind(&event.source.calendar_id)
    // ?12 read-only flag.
    .bind(cols.source_read_only)
    // ?13 last-sync time.
    .bind(cols.source_last_synced_at)
    // ?14 updated-at timestamp.
    .bind(updated_at)
    // ?15 id — selects the row to update.
    .bind(id)
    .execute(pool)
    .await?;

    Ok(())
}

/// Insert-or-update ICS-ingested events, keyed on `(source_calendar_id,
/// source_external_id)`.
///
/// Each event is written with a plain `INSERT ... ON CONFLICT ... DO UPDATE`
/// against `idx_events_source_unique` (migration 0004). `SQLite` requires the
/// conflict target to repeat a partial index's predicate
/// (`WHERE source_calendar_id IS NOT NULL`) or the statement fails at runtime
/// with "ON CONFLICT clause does not match any PRIMARY KEY or UNIQUE
/// constraint" — so the conflict target below carries that predicate. Only the
/// mutable fields are updated on conflict (title, timing, location,
/// recurrence, last-sync time, `updated_at`); identity columns (id, source
/// kind/external id/calendar id, read-only, `created_at`) are left untouched so
/// a re-sync never rewrites an event's origin or history. All events in the
/// slice are written in one transaction.
///
/// # Errors
///
/// Returns `StorageError::Database` on sqlx failure, or `StorageError::Parse`
/// if a timestamp cannot be formatted.
pub async fn upsert_external_events(
    pool: &SqlitePool,
    events: &[Event],
) -> Result<(), StorageError> {
    // One transaction for the whole batch — a partial sync should not leave
    // half the feed's events written and half not.
    let mut tx = pool.begin().await?;

    for event in events {
        let id = event.id.to_string();
        let cols = event_columns(event)?;
        let created_at = format_dt(event.created_at)?;
        let updated_at = format_dt(event.updated_at)?;

        sqlx::query(
            "
            INSERT INTO events (
                id, title, start_at, end_at, all_day, timezone, location,
                recurrence_rrule, recurrence_timezone,
                source_kind, source_external_id, source_calendar_id,
                source_read_only, source_last_synced_at,
                created_at, updated_at
            ) VALUES (
                ?1, ?2, ?3, ?4, ?5, ?6, ?7,
                ?8, ?9,
                ?10, ?11, ?12,
                ?13, ?14,
                ?15, ?16
            )
            ON CONFLICT (source_calendar_id, source_external_id)
                WHERE source_calendar_id IS NOT NULL
            DO UPDATE SET
                title = excluded.title,
                start_at = excluded.start_at,
                end_at = excluded.end_at,
                all_day = excluded.all_day,
                timezone = excluded.timezone,
                location = excluded.location,
                recurrence_rrule = excluded.recurrence_rrule,
                recurrence_timezone = excluded.recurrence_timezone,
                source_last_synced_at = excluded.source_last_synced_at,
                updated_at = excluded.updated_at
            ",
        )
        // Same 16-column bind order as insert_event; on conflict everything
        // but the SET list above (title..updated_at, minus identity columns)
        // is ignored in favour of the existing row's values.
        .bind(id)
        .bind(&event.title)
        .bind(cols.start_at)
        .bind(cols.end_at)
        .bind(cols.all_day)
        .bind(&event.timezone)
        .bind(&event.location)
        .bind(cols.recurrence_rrule)
        .bind(cols.recurrence_timezone)
        .bind(cols.source_kind)
        .bind(&event.source.external_id)
        .bind(&event.source.calendar_id)
        .bind(cols.source_read_only)
        .bind(cols.source_last_synced_at)
        .bind(created_at)
        .bind(updated_at)
        .execute(&mut *tx)
        .await?;
    }

    tx.commit().await?;
    Ok(())
}

/// Delete a calendar's events whose feed UID is not in `keep_external_ids`,
/// and their materialised instances.
///
/// Called after a sync ingests the current feed: `keep_external_ids` is every
/// UID the feed still contains, so anything stored for this calendar but not
/// in that list has vanished from the source and should be removed. An empty
/// `keep_external_ids` (a feed that returned zero events) deletes all of this
/// calendar's events, since nothing survives. `SQLite` has no implicit cascade
/// under STRICT, so instances are deleted before their parent events. Returns
/// the number of `events` rows deleted.
///
/// # Errors
///
/// Returns `StorageError::Database` on sqlx failure.
pub async fn prune_events_missing_from_feed(
    pool: &SqlitePool,
    calendar_id: &str,
    keep_external_ids: &[String],
) -> Result<u64, StorageError> {
    // Both deletes must agree on which rows "vanished", so run them in one
    // transaction against the same predicate.
    let mut tx = pool.begin().await?;

    // Bind ?1 = calendar_id, then one placeholder per kept UID. With no kept
    // UIDs the NOT IN clause is dropped entirely (an empty `NOT IN ()` is
    // invalid SQL, and its intended meaning — "nothing survives" — is exactly
    // "delete every event for this calendar").
    let predicate = if keep_external_ids.is_empty() {
        String::new()
    } else {
        let placeholders: Vec<String> = (0..keep_external_ids.len())
            .map(|i| format!("?{}", i + 2))
            .collect();
        format!(
            " AND source_external_id NOT IN ({})",
            placeholders.join(", ")
        )
    };

    let instances_sql = format!(
        "
        DELETE FROM event_instances
        WHERE event_id IN (
            SELECT id FROM events WHERE source_calendar_id = ?1{predicate}
        )
        "
    );
    let mut instances_query = sqlx::query(&instances_sql).bind(calendar_id);
    for uid in keep_external_ids {
        instances_query = instances_query.bind(uid);
    }
    instances_query.execute(&mut *tx).await?;

    let events_sql = format!("DELETE FROM events WHERE source_calendar_id = ?1{predicate}");
    let mut events_query = sqlx::query(&events_sql).bind(calendar_id);
    for uid in keep_external_ids {
        events_query = events_query.bind(uid);
    }
    let result = events_query.execute(&mut *tx).await?;

    tx.commit().await?;
    Ok(result.rows_affected())
}

// ─── Private helpers ──────────────────────────────────────────────────────────

/// The subset of an event's columns that need transformation (bool → 0/1,
/// enum → its storage string, `OffsetDateTime` → RFC 3339 TEXT) rather than a
/// plain borrow.
///
/// `id`, `title`, `timezone`, `location`, and the two `source_*` id fields
/// bind directly from `&event.*` at each call site (no conversion needed), so
/// they are not part of this struct — only the fields `insert_event`,
/// `update_event`, and `upsert_external_events` would otherwise each compute
/// by hand are pulled out here, so the three write paths cannot drift on how
/// one of them is encoded.
struct EventColumns {
    /// RFC 3339 TEXT start instant.
    start_at: String,
    /// RFC 3339 TEXT end instant, or `None` for SQL NULL.
    end_at: Option<String>,
    /// All-day flag as INTEGER 0/1.
    all_day: i64,
    /// RRULE string, or `None` when one-shot/external.
    recurrence_rrule: Option<String>,
    /// Recurrence timezone, present iff `recurrence_rrule` is.
    recurrence_timezone: Option<String>,
    /// `'native' | 'ics'`.
    source_kind: String,
    /// Read-only flag as INTEGER 0/1.
    source_read_only: i64,
    /// RFC 3339 TEXT last-sync time, or `None` for native events.
    source_last_synced_at: Option<String>,
}

/// Compute the transformed columns shared by every event write path.
///
/// # Errors
///
/// Returns `StorageError::Parse` if `start_at`, `end_at`, or
/// `source.last_synced_at` cannot be formatted as RFC 3339.
fn event_columns(event: &Event) -> Result<EventColumns, StorageError> {
    Ok(EventColumns {
        // Required start → RFC 3339 TEXT.
        start_at: format_dt(event.start_at)?,
        // Optional end → RFC 3339 TEXT or None.
        end_at: format_optional_dt(event.end_at)?,
        // Booleans are stored as INTEGER 0/1 under STRICT mode.
        all_day: i64::from(event.all_day),
        // Recurrence: both columns present together, or both NULL.
        recurrence_rrule: event.recurrence.as_ref().map(|r| r.rrule.clone()),
        recurrence_timezone: event.recurrence.as_ref().map(|r| r.timezone.clone()),
        // Enum → 'native' | 'ics'.
        source_kind: event.source.kind.to_string(),
        // Read-only flag → 0/1.
        source_read_only: i64::from(event.source.read_only),
        // Optional last-sync time → RFC 3339 TEXT or None.
        source_last_synced_at: format_optional_dt(event.source.last_synced_at)?,
    })
}

/// Column list + FROM for the `events` table. Single source of truth for the
/// select shape; `fetch_event` appends `WHERE id = ?1` and `list_events` an
/// `ORDER BY`, so the column list is never duplicated.
const EVENT_SELECT: &str = "
    SELECT id, title, start_at, end_at, all_day, timezone, location,
           recurrence_rrule, recurrence_timezone,
           source_kind, source_external_id, source_calendar_id,
           source_read_only, source_last_synced_at, created_at, updated_at
    FROM   events
";

/// Convert a raw database row into an `Event`.
///
/// Parsing is strict: the first field that fails aborts the whole row, because a
/// partially-constructed event would be more dangerous than a visible error, and
/// the `Vec`-returning callers stop on the first error rather than silently
/// skipping a corrupt row. The parse order follows the SELECT column order so an
/// error message's field name lines up with the query for easy tracing.
fn row_to_event(row: EventRow) -> Result<Event, StorageError> {
    // Parse the primary key (UUID TEXT → typed newtype).
    let id = row
        .id
        .parse::<EventId>()
        .map_err(|e| StorageError::Parse(format!("event id: {e}")))?;
    // Required start instant.
    let start_at = parse_rfc3339(&row.start_at, "start_at")?;
    // Audit timestamps.
    let created_at = parse_rfc3339(&row.created_at, "created_at")?;
    let updated_at = parse_rfc3339(&row.updated_at, "updated_at")?;

    // Optional end timestamp (None when the column is NULL).
    let end_at = row
        .end_at
        .map(|s| parse_rfc3339(&s, "end_at"))
        .transpose()?;

    // Reconstruct the recurrence rule from the two nullable columns.
    let recurrence = match (row.recurrence_rrule, row.recurrence_timezone) {
        // Both present: a recurring event.
        (Some(rrule), Some(tz)) => Some(RecurrenceRule::new(rrule, tz)),
        // Both NULL: one-shot (or external).
        (None, None) => None,
        // Exactly one present: inconsistent state.
        _ => {
            return Err(StorageError::Parse(
                "recurrence_rrule and recurrence_timezone must both be NULL or both non-NULL"
                    .to_owned(),
            ));
        }
    };

    // Reconstruct the source from the flattened source_* columns.
    // The kind string parses back into the enum.
    let kind = row
        .source_kind
        .parse::<EventSourceKind>()
        .map_err(|e| StorageError::Parse(format!("source_kind: {e}")))?;
    // Optional last-sync time (None for native events).
    let last_synced_at = row
        .source_last_synced_at
        .map(|s| parse_rfc3339(&s, "source_last_synced_at"))
        .transpose()?;
    // Assemble the source; external ids stay as stored, read-only maps from 0/1.
    let source = EventSource {
        kind,
        external_id: row.source_external_id,
        calendar_id: row.source_calendar_id,
        // INTEGER 0/1 back to bool.
        read_only: row.source_read_only != 0,
        last_synced_at,
    };

    // Direct struct construction — the builder invariants held at insert time,
    // so no re-validation is needed on read.
    Ok(Event {
        // Parsed above.
        id,
        // Title stored verbatim; no transformation on read.
        title: row.title,
        // Parsed start/end instants.
        start_at,
        end_at,
        // INTEGER 0/1 back to bool.
        all_day: row.all_day != 0,
        // Timezone and location pass through as-is.
        timezone: row.timezone,
        location: row.location,
        // Reconstructed recurrence rule (Some/None).
        recurrence,
        // Reconstructed source (kind, ids, read-only, last sync).
        source,
        // Parsed audit timestamps.
        created_at,
        updated_at,
    })
}

/// Format a required `OffsetDateTime` as RFC 3339 TEXT.
///
/// Used for the non-null timestamp columns (`start_at`, `created_at`, `updated_at`).
fn format_dt(dt: OffsetDateTime) -> Result<String, StorageError> {
    // RFC 3339 is lexicographically sortable — good for ORDER BY start_at.
    dt.format(&Rfc3339)
        .map_err(|e| StorageError::Parse(e.to_string()))
}

/// Format an optional `OffsetDateTime` as RFC 3339, or `None` for SQL NULL.
///
/// Preserves the `Option`: a `None` input binds as NULL, so it is used for the
/// nullable timestamp columns (`end_at`, `source_last_synced_at`).
fn format_optional_dt(dt: Option<OffsetDateTime>) -> Result<Option<String>, StorageError> {
    // Present → format; absent → None (binds as NULL).
    dt.map(|t| {
        t.format(&Rfc3339)
            .map_err(|e| StorageError::Parse(e.to_string()))
    })
    .transpose()
}

/// Parse an RFC 3339 string into `OffsetDateTime`, naming the column on failure.
///
/// The `column` argument appears in the error so a malformed stored value is
/// easy to trace back to its source.
fn parse_rfc3339(s: &str, column: &str) -> Result<OffsetDateTime, StorageError> {
    // RFC 3339 carries a mandatory offset, so the result keeps timezone info.
    OffsetDateTime::parse(s, &Rfc3339).map_err(|e| StorageError::Parse(format!("{column}: {e}")))
}
