// member.rs — repository functions for the Member entity.
//
// The storage layer's interface for the household's display registry. It
// exposes:
//   • insert_member — write a new member
//   • list_members  — read all members (no filter — the roster is small)
//   • fetch_member  — read one member by id
//   • delete_member — remove a member by id
//
// No business logic lives here; `amity_core::member::Member` and its builder
// own every invariant (non-empty display_name, colour parsing). This module's
// job ends at handing rows back and forth. See migration 0006.
//
// Storage layout notes:
//   • `members` has no child table and no update path in this slice — Slice 1
//     is create/list/fetch/delete only (mirrors `pantry.rs`, the simplest
//     existing repository).
//   • Datetimes are RFC 3339 TEXT, matching every other table in this crate.
//   • Existing MemberId values elsewhere in the database (Task.owner_id,
//     Meal.cook_id, …) may reference no row here — that is expected, and this
//     module does nothing special for it; a dangling id simply yields `None`
//     from `fetch_member`.

// `SqlitePool` is the shared pool injected into every query function.
use sqlx::SqlitePool;
// `OffsetDateTime` is the canonical timestamp type; RFC 3339 is the storage form.
use time::OffsetDateTime;
// The RFC 3339 format descriptor used for both serialisation and deserialisation.
use time::format_description::well_known::Rfc3339;

// Domain types this module reads/writes.
use amity_core::ids::MemberId;
use amity_core::member::{Member, MemberColor};

// `StorageError` wraps sqlx errors and field-parse failures.
use crate::StorageError;

// ─── Row type ────────────────────────────────────────────────────────────────

/// Raw database row from the `members` table.
///
/// Every field is `String`/`Option<String>` because the database stores
/// everything as TEXT — there is no typed UUID or datetime column to lean on.
/// Field names must match the SQL columns exactly for `sqlx::FromRow` to map
/// them without a `#[sqlx(rename = "…")]` annotation.
#[derive(sqlx::FromRow)]
struct MemberRow {
    // UUID TEXT — the member's primary key.
    id: String,
    // The member's display name.
    display_name: String,
    // Optional short label, or NULL.
    initial: Option<String>,
    // snake_case MemberColor string, or NULL.
    color: Option<String>,
    // RFC 3339 TEXT creation timestamp.
    created_at: String,
}

// ─── Public repository functions ─────────────────────────────────────────────

/// Insert a new member.
///
/// All fields come from the `Member` struct; the id and `created_at` are
/// generated by the domain layer (`MemberBuilder::build`), so this function
/// neither reads the clock nor generates ids.
///
/// # Errors
///
/// Returns `StorageError::Database` on any sqlx failure (e.g. a UUID
/// primary-key violation), or `StorageError::Parse` if the creation timestamp
/// cannot be formatted.
pub async fn insert_member(pool: &SqlitePool, member: &Member) -> Result<(), StorageError> {
    // UUID newtype → hyphenated string.
    let id = member.id.to_string();
    let created_at = format_dt(member.created_at)?;
    // Colour, if present, becomes its snake_case storage string.
    let color = member.color.map(|c| c.to_string());

    sqlx::query(
        "INSERT INTO members (id, display_name, initial, color, created_at) \
         VALUES (?1, ?2, ?3, ?4, ?5)",
    )
    // ?1 primary key.
    .bind(id)
    // ?2 display name (already validated non-empty by the domain layer).
    .bind(&member.display_name)
    // ?3 initial, or SQL NULL.
    .bind(&member.initial)
    // ?4 color, or SQL NULL.
    .bind(color)
    // ?5 creation timestamp.
    .bind(created_at)
    .execute(pool)
    .await?;

    Ok(())
}

/// List all members, in no particular guaranteed order beyond insertion.
///
/// At household scale the member roster is a short, static set of people, so
/// a full unordered scan is simplest; callers that need a display order sort
/// in the service layer.
///
/// # Errors
///
/// Returns `StorageError::Database` on sqlx failure, or `StorageError::Parse`
/// if a stored row cannot be decoded.
pub async fn list_members(pool: &SqlitePool) -> Result<Vec<Member>, StorageError> {
    let rows: Vec<MemberRow> = sqlx::query_as(MEMBER_SELECT).fetch_all(pool).await?;

    // Parse each row; stop at the first error rather than skipping a corrupt row.
    rows.into_iter().map(row_to_member).collect()
}

/// Fetch a single member by id.
///
/// Returns `None` when no member has that id — a non-exceptional "not found"
/// the caller maps to a 404 (or, for a dangling cook/assignee reference,
/// renders neutrally) as it sees fit.
///
/// # Errors
///
/// Returns `StorageError::Database` on sqlx failure, or `StorageError::Parse`
/// if the stored row cannot be decoded.
pub async fn fetch_member(pool: &SqlitePool, id: MemberId) -> Result<Option<Member>, StorageError> {
    let id_str = id.to_string();

    // Append the WHERE clause to the shared column list via format!, since
    // concat! requires a literal and MEMBER_SELECT is a const &str.
    let sql = format!("{MEMBER_SELECT} WHERE id = ?1");
    let row: Option<MemberRow> = sqlx::query_as(&sql)
        .bind(id_str)
        .fetch_optional(pool)
        .await?;

    match row {
        Some(r) => Ok(Some(row_to_member(r)?)),
        None => Ok(None),
    }
}

/// Delete a member by id.
///
/// Returns whether a row matched (`false` for an unknown id) so the caller
/// can distinguish "deleted" from "nothing to delete" without a separate
/// existence check. This does not touch any Task/Meal rows that reference the
/// deleted id — those become dangling references, which is expected (see the
/// module doc); no cascade or nulling happens here.
///
/// # Errors
///
/// Returns `StorageError::Database` on sqlx failure.
pub async fn delete_member(pool: &SqlitePool, id: MemberId) -> Result<bool, StorageError> {
    let id_str = id.to_string();

    let result = sqlx::query("DELETE FROM members WHERE id = ?1")
        .bind(id_str)
        .execute(pool)
        .await?;

    // rows_affected() is 0 or 1 since id is the primary key.
    Ok(result.rows_affected() > 0)
}

// ─── Private helpers ──────────────────────────────────────────────────────────

/// Column list + FROM for the `members` table. Single source of truth for the
/// select shape; `fetch_member` appends `WHERE id = ?1` via `format!` (never
/// `concat!`, which needs a compile-time literal), so the column list is
/// never duplicated.
const MEMBER_SELECT: &str = "SELECT id, display_name, initial, color, created_at FROM members";

/// Convert a raw database row into a `Member`.
///
/// Parsing is strict: the first field that fails aborts the whole row,
/// because a partially-constructed member would be more dangerous than a
/// visible error, and `list_members` stops on the first error rather than
/// silently skipping a corrupt row.
fn row_to_member(row: MemberRow) -> Result<Member, StorageError> {
    // Parse the primary key (UUID TEXT → typed newtype).
    let id = row
        .id
        .parse::<MemberId>()
        .map_err(|e| StorageError::Parse(format!("member id: {e}")))?;
    // Optional colour: parse only when present.
    let color = row
        .color
        .map(|c| c.parse::<MemberColor>())
        .transpose()
        .map_err(|e| StorageError::Parse(format!("color: {e}")))?;
    // Required creation timestamp.
    let created_at = parse_rfc3339(&row.created_at, "created_at")?;

    // Direct struct construction — the builder invariants held at insert
    // time, so no re-validation is needed on read.
    Ok(Member {
        id,
        // Name and initial pass through as-is; no transformation on read.
        display_name: row.display_name,
        initial: row.initial,
        color,
        created_at,
    })
}

/// Format a required `OffsetDateTime` as RFC 3339 TEXT.
fn format_dt(dt: OffsetDateTime) -> Result<String, StorageError> {
    dt.format(&Rfc3339)
        .map_err(|e| StorageError::Parse(e.to_string()))
}

/// Parse an RFC 3339 string into `OffsetDateTime`, naming the column on failure.
fn parse_rfc3339(s: &str, column: &str) -> Result<OffsetDateTime, StorageError> {
    OffsetDateTime::parse(s, &Rfc3339).map_err(|e| StorageError::Parse(format!("{column}: {e}")))
}
