// pantry.rs — repository functions for the PantryItem entity.
//
// The storage layer's interface for the household's staples memory. It
// exposes:
//   • insert_pantry_item — write a new staple
//   • list_pantry_items  — read all staples (no filter — the list is small)
//   • delete_pantry_item — remove a staple by id
//
// No business logic lives here; `plan_grocery_additions` (amity_core::grocery)
// is the only consumer of the resulting `Vec<PantryItem>`, and it is pure —
// this module's job ends at handing back the rows. See migration 0005.
//
// Storage layout notes:
//   • `pantry_items` has no child table and no update path — PantryItem is
//     the simplest of the three P2 Slice 2 entities (see amity_core::pantry).
//   • Datetimes are RFC 3339 TEXT, matching every other table in this crate.

// `SqlitePool` is the shared pool injected into every query function.
use sqlx::SqlitePool;
// `OffsetDateTime` is the canonical timestamp type; RFC 3339 is the storage form.
use time::OffsetDateTime;
// The RFC 3339 format descriptor used for both serialisation and deserialisation.
use time::format_description::well_known::Rfc3339;

// Domain type this module reads/writes.
use amity_core::ids::PantryItemId;
use amity_core::pantry::PantryItem;

// `StorageError` wraps sqlx errors and field-parse failures.
use crate::StorageError;

// ─── Row type ────────────────────────────────────────────────────────────────

/// Raw database row from the `pantry_items` table.
///
/// Every field is `String`/`Option<String>` because the database stores
/// everything as TEXT — there is no typed UUID or datetime column to lean on.
/// Field names must match the SQL columns exactly for `sqlx::FromRow` to map
/// them without a `#[sqlx(rename = "…")]` annotation.
#[derive(sqlx::FromRow)]
struct PantryItemRow {
    // UUID TEXT — the item's primary key.
    id: String,
    // The staple's name.
    name: String,
    // Optional free-form note, or NULL.
    note: Option<String>,
    // RFC 3339 TEXT creation timestamp.
    created_at: String,
}

// ─── Public repository functions ─────────────────────────────────────────────

/// Insert a new pantry item.
///
/// All fields come from the `PantryItem` struct; the id and `created_at` are
/// generated by the domain layer (`PantryItemBuilder::build`), so this
/// function neither reads the clock nor generates ids.
///
/// # Errors
///
/// Returns `StorageError::Database` on any sqlx failure (e.g. a UUID
/// primary-key violation), or `StorageError::Parse` if the creation timestamp
/// cannot be formatted.
pub async fn insert_pantry_item(pool: &SqlitePool, item: &PantryItem) -> Result<(), StorageError> {
    // UUID newtype → hyphenated string.
    let id = item.id.to_string();
    let created_at = format_dt(item.created_at)?;

    sqlx::query("INSERT INTO pantry_items (id, name, note, created_at) VALUES (?1, ?2, ?3, ?4)")
        // ?1 primary key.
        .bind(id)
        // ?2 name (already validated non-empty by the domain layer).
        .bind(&item.name)
        // ?3 note, or SQL NULL.
        .bind(&item.note)
        // ?4 creation timestamp.
        .bind(created_at)
        .execute(pool)
        .await?;

    Ok(())
}

/// List all pantry items, in no particular guaranteed order beyond insertion.
///
/// At household scale the pantry list is a short, static set of staples, so
/// a full unordered scan is simplest; callers that need a display order sort
/// in the service layer.
///
/// # Errors
///
/// Returns `StorageError::Database` on sqlx failure, or `StorageError::Parse`
/// if a stored row cannot be decoded.
pub async fn list_pantry_items(pool: &SqlitePool) -> Result<Vec<PantryItem>, StorageError> {
    let rows: Vec<PantryItemRow> = sqlx::query_as(PANTRY_ITEM_SELECT).fetch_all(pool).await?;

    // Parse each row; stop at the first error rather than skipping a corrupt row.
    rows.into_iter().map(row_to_pantry_item).collect()
}

/// Delete a pantry item by id.
///
/// Returns whether a row matched (`false` for an unknown id) so the caller
/// can distinguish "deleted" from "nothing to delete" without a separate
/// existence check. There is no cascade to worry about — pantry items have
/// no child rows.
///
/// # Errors
///
/// Returns `StorageError::Database` on sqlx failure.
pub async fn delete_pantry_item(pool: &SqlitePool, id: PantryItemId) -> Result<bool, StorageError> {
    let id_str = id.to_string();

    let result = sqlx::query("DELETE FROM pantry_items WHERE id = ?1")
        .bind(id_str)
        .execute(pool)
        .await?;

    // rows_affected() is 0 or 1 since id is the primary key.
    Ok(result.rows_affected() > 0)
}

// ─── Private helpers ──────────────────────────────────────────────────────────

/// Column list + FROM for the `pantry_items` table. Single source of truth
/// for the select shape; there is only one read path (`list_pantry_items`),
/// but the const mirrors the pattern used by every other repository module.
const PANTRY_ITEM_SELECT: &str = "SELECT id, name, note, created_at FROM pantry_items";

/// Convert a raw database row into a `PantryItem`.
///
/// Parsing is strict: the first field that fails aborts the whole row,
/// because a partially-constructed item would be more dangerous than a
/// visible error, and `list_pantry_items` stops on the first error rather
/// than silently skipping a corrupt row.
fn row_to_pantry_item(row: PantryItemRow) -> Result<PantryItem, StorageError> {
    // Parse the primary key (UUID TEXT → typed newtype).
    let id = row
        .id
        .parse::<PantryItemId>()
        .map_err(|e| StorageError::Parse(format!("pantry item id: {e}")))?;
    // Required creation timestamp.
    let created_at = parse_rfc3339(&row.created_at, "created_at")?;

    // Direct struct construction — the builder invariants held at insert
    // time, so no re-validation is needed on read.
    Ok(PantryItem {
        id,
        // Name and note pass through as-is; no transformation on read.
        name: row.name,
        note: row.note,
        created_at,
    })
}

/// Format a required `OffsetDateTime` as RFC 3339 TEXT.
fn format_dt(dt: OffsetDateTime) -> Result<String, StorageError> {
    dt.format(&Rfc3339)
        .map_err(|e| StorageError::Parse(e.to_string()))
}

/// Parse an RFC 3339 string into `OffsetDateTime`, naming the column on failure.
fn parse_rfc3339(s: &str, column: &str) -> Result<OffsetDateTime, StorageError> {
    OffsetDateTime::parse(s, &Rfc3339).map_err(|e| StorageError::Parse(format!("{column}: {e}")))
}
