// task_instance.rs — repository functions for the task_instances table.
//
// Task instances are materialised records of future scheduled occurrences of
// recurring tasks. A background job extends the horizon up to 60 days ahead
// and prunes instances older than 30 days (see ADR-0002 §materialisation-strategy).
//
// This module exposes:
//   • upsert_task_instances     — bulk insert (INSERT OR IGNORE) new instances
//   • list_upcoming_instances   — next N instances for a task, ordered by date
//   • prune_old_instances       — delete instances older than a given cutoff
//   • delete_future_instances   — delete all instances at or after a point in time
//                                 (used when recurrence rule changes mid-flight)
//
// Each instance row has a `UNIQUE (task_id, scheduled_at)` constraint so that
// running the materialiser twice is idempotent — `INSERT OR IGNORE` skips
// duplicates without error (see migration 0002 §task_instances).
//
// No business logic lives here. The materialiser that produces the
// `OffsetDateTime` list is in `amity_core::recurrence_materialiser`.
// This module only persists what it is given.

// `SqlitePool` is the shared connection pool passed into all async queries.
use sqlx::SqlitePool;
// `OffsetDateTime` is the project's canonical datetime type, used for scheduled_at.
use time::OffsetDateTime;
// RFC 3339 is the serialisation format for all timestamp columns in this table.
use time::format_description::well_known::Rfc3339;

// `MemberId` for the nullable assignee; `TaskId` for the parent task reference.
use amity_core::ids::{MemberId, TaskId};

// `StorageError` wraps both sqlx database errors and field-level parse errors.
use crate::StorageError;

// ─── Public types ─────────────────────────────────────────────────────────────

/// A materialised instance of a recurring task, ready for storage.
///
/// `TaskInstance` is a storage-layer type, not a domain type. It carries
/// just enough data to populate a `task_instances` row. The materialiser in
/// `amity_core::recurrence_materialiser` produces these values; this module
/// persists them. There is intentionally no domain logic in this struct.
#[derive(Debug, Clone)]
pub struct TaskInstance {
    /// UUID v7 for this instance (generated by the caller before insertion).
    pub id: String,

    /// The parent recurring task.
    pub task_id: TaskId,

    /// When this instance is scheduled; must include a timezone offset.
    pub scheduled_at: OffsetDateTime,

    /// Default assignee for this specific instance. Inherits from the parent
    /// task's `current_assignee_id`; may be None when no default is set.
    pub current_assignee_id: Option<MemberId>,
}

// ─── Row type ─────────────────────────────────────────────────────────────────

/// Raw database row from the `task_instances` table.
///
/// Field names match the SQL column names so that `#[derive(sqlx::FromRow)]`
/// maps them automatically without a `#[sqlx(rename = "...")]` annotation.
/// All timestamp fields are stored as RFC 3339 TEXT; the assignee is UUID TEXT
/// or NULL when no default assignee has been set on the task.
#[derive(sqlx::FromRow)]
struct TaskInstanceRow {
    // UUID v7 TEXT — unique ID for this instance.
    id: String,
    // UUID TEXT — the parent recurring task.
    task_id: String,
    // RFC 3339 TEXT with timezone offset — when this occurrence is scheduled.
    scheduled_at: String,
    // UUID TEXT NULL — default assignee, inherited or explicit.
    current_assignee_id: Option<String>,
}

// ─── Public repository functions ─────────────────────────────────────────────

/// Bulk-insert materialised task instances.
///
/// Uses `INSERT OR IGNORE` so that running the materialiser twice for the same
/// time window is idempotent — duplicate `(task_id, scheduled_at)` rows are
/// silently skipped. The unique constraint in the schema enforces deduplication
/// at the database level.
///
/// The caller is responsible for generating the `id` field (UUID v7 string) for
/// each instance before passing it here. The service layer calls
/// `uuid::Uuid::now_v7().to_string()` for each new instance.
///
/// Instances are inserted one at a time rather than in a batch INSERT because
/// the scale of a household task scheduler (60-day horizon, ≤1 task/day) does
/// not justify the complexity of bulk binding. Error reporting is also clearer
/// when each instance is inserted individually.
///
/// # Errors
///
/// Returns `StorageError::Database` if the insert fails for reasons other than
/// a uniqueness conflict (e.g. FK violation, STRICT column type mismatch).
/// Returns `StorageError::Parse` if a timestamp cannot be formatted.
pub async fn upsert_task_instances(
    pool: &SqlitePool,
    instances: &[TaskInstance],
) -> Result<(), StorageError> {
    // Insert each instance individually; batching is not necessary at the
    // scale of a household task scheduler and keeps error reporting clear.
    for instance in instances {
        let scheduled_str = instance
            .scheduled_at
            .format(&Rfc3339)
            .map_err(|e| StorageError::Parse(e.to_string()))?;
        let task_id_str = instance.task_id.to_string();
        let assignee_str = instance.current_assignee_id.map(|m| m.to_string());

        // INSERT OR IGNORE: skip if (task_id, scheduled_at) already exists.
        sqlx::query(
            "
            INSERT OR IGNORE INTO task_instances
                (id, task_id, scheduled_at, current_assignee_id)
            VALUES (?1, ?2, ?3, ?4)
            ",
        )
        .bind(&instance.id)
        .bind(task_id_str)
        .bind(scheduled_str)
        .bind(assignee_str)
        .execute(pool)
        .await?;
    }

    Ok(())
}

/// List the next N upcoming instances for a task, ordered by `scheduled_at ASC`.
///
/// Returns the nearest `limit` instances that are scheduled on or after `from`.
/// Passing `from` as "now" gives the upcoming-tasks surfacing query (brief §8).
///
/// The `limit` parameter prevents unbounded result sets. The service layer
/// caps it at 100 and defaults to 20. A limit of 1 is the most efficient
/// way to find just the next upcoming instance for a single task.
///
/// # Errors
///
/// Returns `StorageError` on database or parse failures.
pub async fn list_upcoming_instances(
    pool: &SqlitePool,
    task_id: TaskId,
    from: OffsetDateTime,
    limit: i64,
) -> Result<Vec<TaskInstance>, StorageError> {
    let task_id_str = task_id.to_string();
    // Format the lower bound as RFC 3339 TEXT for the >= comparison.
    let from_str = from
        .format(&Rfc3339)
        .map_err(|e| StorageError::Parse(e.to_string()))?;

    let rows: Vec<TaskInstanceRow> = sqlx::query_as(
        "
        SELECT id, task_id, scheduled_at, current_assignee_id
        FROM   task_instances
        WHERE  task_id = ?1 AND scheduled_at >= ?2
        ORDER  BY scheduled_at ASC
        LIMIT  ?3
        ",
    )
    .bind(task_id_str)
    .bind(from_str)
    .bind(limit)
    .fetch_all(pool)
    .await?;

    rows.into_iter().map(row_to_task_instance).collect()
}

/// Delete all task instances with `scheduled_at < cutoff`.
///
/// Used by the background pruning job to remove instances older than 30 days.
/// Pruning is safe because completion events write to `completion_logs`, not to
/// `task_instances` — the completion history is preserved even after the
/// corresponding instance row is pruned.
///
/// The typical call is `prune_old_instances(pool, OffsetDateTime::now_utc() - 30.days())`.
/// The cutoff is supplied by the caller so that tests can use arbitrary dates.
///
/// # Errors
///
/// Returns `StorageError::Database` on sqlx failure.
pub async fn prune_old_instances(
    pool: &SqlitePool,
    cutoff: OffsetDateTime,
) -> Result<u64, StorageError> {
    let cutoff_str = cutoff
        .format(&Rfc3339)
        .map_err(|e| StorageError::Parse(e.to_string()))?;

    let result = sqlx::query("DELETE FROM task_instances WHERE scheduled_at < ?1")
        .bind(cutoff_str)
        .execute(pool)
        .await?;

    // Return the number of rows removed so the caller can log the pruning count.
    // This value is also useful for metrics and alerting on unexpected spikes.
    Ok(result.rows_affected())
}

/// Delete all task instances for a task scheduled at or after `from`.
///
/// Called when the recurrence rule is changed mid-flight (ADR-0002
/// §mid-flight-recurrence-change). After deleting the future instances,
/// the caller re-materialises from the new rule and calls `upsert_task_instances`.
///
/// This does NOT affect instances before `from` or `completion_logs` — already
/// scheduled and completed instances are preserved to maintain an accurate history.
/// Only unmaterialised future slots are swept so the new rule can fill them.
///
/// # Errors
///
/// Returns `StorageError::Database` on sqlx failure.
pub async fn delete_future_instances(
    pool: &SqlitePool,
    task_id: TaskId,
    from: OffsetDateTime,
) -> Result<u64, StorageError> {
    let task_id_str = task_id.to_string();
    let from_str = from
        .format(&Rfc3339)
        .map_err(|e| StorageError::Parse(e.to_string()))?;

    let result =
        sqlx::query("DELETE FROM task_instances WHERE task_id = ?1 AND scheduled_at >= ?2")
            .bind(task_id_str)
            .bind(from_str)
            .execute(pool)
            .await?;

    Ok(result.rows_affected())
}

// ─── Private helpers ──────────────────────────────────────────────────────────

/// Convert a raw database row into a `TaskInstance`.
///
/// Parses the UUID strings and the RFC 3339 timestamp. Returns the first error
/// encountered; all fields must parse successfully for the instance to be used.
fn row_to_task_instance(row: TaskInstanceRow) -> Result<TaskInstance, StorageError> {
    // Parse the task UUID.
    let task_id = row
        .task_id
        .parse::<TaskId>()
        .map_err(|e| StorageError::Parse(format!("task_id: {e}")))?;

    // Parse the RFC 3339 timestamp for scheduled_at.
    let scheduled_at = OffsetDateTime::parse(&row.scheduled_at, &Rfc3339)
        .map_err(|e| StorageError::Parse(format!("scheduled_at: {e}")))?;

    // Parse the optional assignee UUID. None is valid and common — it means
    // no default assignee has been set for this specific instance.
    let current_assignee_id = row
        .current_assignee_id
        .map(|s| {
            s.parse::<MemberId>()
                .map_err(|e| StorageError::Parse(format!("current_assignee_id: {e}")))
        })
        .transpose()?;

    Ok(TaskInstance {
        id: row.id,
        task_id,
        scheduled_at,
        current_assignee_id,
    })
}
