// grocery.rs — GroceryList, GroceryItem, and the grocery-generation function.
//
// This module is the heart of P2 Slice 1: it turns planned `Meal`s into
// grocery additions while respecting two no-clobber invariants — pantry
// staples are never suggested, and items already on the list (manual or
// generated, checked or unchecked) are never duplicated or touched.
//
// This module defines:
//   • `GrocerySource`         — enum: Manual | FromMeal, snake_case Display/FromStr.
//   • `GroceryList`           — a named list (fields pub for storage reconstruction).
//   • `GroceryListBuilder`    — validates non-empty name.
//   • `GroceryItem`           — one line on a list.
//   • `GroceryItemBuilder`    — validates non-empty name.
//   • `GroceryError`          — error variants for both builders and parsing.
//   • `plan_grocery_additions` — the pure generation function (see its doc).
//
// No recipes, thresholds, or cook-assignment logic live here — this phase's
// design is fixed to exactly this scope (see the P2 Slice 1 brief).

// Serde derives for JSON API and database round-trips.
use serde::{Deserialize, Serialize};
// OffsetDateTime for `created_at`.
use time::OffsetDateTime;

// Typed IDs for this entity and the entities it references.
use crate::ids::{GroceryItemId, GroceryListId, MealId};
// Meal and PantryItem are the inputs to plan_grocery_additions.
use crate::meal::Meal;
use crate::pantry::PantryItem;

// ─── GrocerySource ──────────────────────────────────────────────────────────

/// Where a `GroceryItem` came from.
///
/// `Manual` items are typed directly onto the list by a household member.
/// `FromMeal` items were generated by `plan_grocery_additions` from a
/// planned meal's ingredient lines — `source_meal_id` names which meal.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum GrocerySource {
    /// Typed directly onto the list by a household member.
    Manual,
    /// Generated from a planned meal's ingredient lines.
    FromMeal,
}

impl std::fmt::Display for GrocerySource {
    /// Produce the `snake_case` storage string.
    ///
    /// These strings are the database storage contract. Changing them requires
    /// a migration to backfill existing rows.
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        // Manual match keeps this independent of serde for SQL bind parameters.
        let s = match self {
            Self::Manual => "manual",
            Self::FromMeal => "from_meal",
        };
        write!(f, "{s}")
    }
}

impl std::str::FromStr for GrocerySource {
    type Err = GroceryError;

    /// Parse the `snake_case` storage string back into the enum.
    ///
    /// # Errors
    ///
    /// Returns [`GroceryError::UnknownSource`] if the string is not a known variant.
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        // Each arm mirrors the Display impl above for round-trip safety.
        match s {
            "manual" => Ok(Self::Manual),
            "from_meal" => Ok(Self::FromMeal),
            other => Err(GroceryError::UnknownSource(other.to_owned())),
        }
    }
}

// ─── GroceryList ────────────────────────────────────────────────────────────

/// A named grocery list.
///
/// Construction goes through [`GroceryListBuilder`]. Direct field construction
/// is `pub` so the storage layer can reconstruct lists from database rows.
/// The default name ("Groceries") is a service-layer concern, not enforced
/// here — this builder validates whatever name the caller supplies.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct GroceryList {
    /// Globally unique, time-ordered identifier.
    pub id: GroceryListId,
    /// The list's name. Must not be empty after trimming.
    pub name: String,
    /// When this list was first created.
    pub created_at: OffsetDateTime,
}

/// Builder for [`GroceryList`].
///
/// Enforces the invariants the struct requires:
/// - `name` must not be empty after trimming.
/// - `now` must be set (used for `created_at`).
#[derive(Debug)]
pub struct GroceryListBuilder {
    /// The list's name. Required; validated on `build()`.
    name: Option<String>,
    /// Caller-supplied id, used by the storage layer to reconstruct a row
    /// with its existing id rather than minting a fresh one.
    id: Option<GroceryListId>,
    /// Current wall-clock time for `created_at`. Required.
    now: Option<OffsetDateTime>,
}

impl GroceryListBuilder {
    /// Start building a new grocery list with the given name.
    ///
    /// Callers who want the default "Groceries" name pass it explicitly —
    /// that default lives in the service layer, not here.
    #[must_use]
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            // Store as-is; the non-empty check happens in build().
            name: Some(name.into()),
            // No caller-supplied id unless the storage layer sets one.
            id: None,
            // now must be supplied for deterministic timestamps.
            now: None,
        }
    }

    /// Supply a specific id (used by the storage layer to reconstruct a row
    /// with its existing id). Production callers creating a brand-new list
    /// should not call this — `build()` mints a fresh id when absent.
    #[must_use]
    pub fn id(mut self, id: GroceryListId) -> Self {
        self.id = Some(id);
        self
    }

    /// Supply the current wall-clock time for `created_at` (required).
    #[must_use]
    pub fn now(mut self, now: OffsetDateTime) -> Self {
        self.now = Some(now);
        self
    }

    /// Validate all invariants and construct the `GroceryList`.
    ///
    /// # Errors
    ///
    /// Returns [`GroceryError::EmptyName`] if the name is blank.
    /// Returns [`GroceryError::MissingNow`] if `now` was not set.
    pub fn build(self) -> Result<GroceryList, GroceryError> {
        // Name is set unconditionally in new(); validate its trimmed form.
        let name = self.name.unwrap_or_default();
        if name.trim().is_empty() {
            return Err(GroceryError::EmptyName);
        }

        // now is required for a complete GroceryList.
        let now = self.now.ok_or(GroceryError::MissingNow)?;

        // Use the caller-supplied id (storage reconstruction) or mint a
        // fresh time-ordered one (new-list construction).
        let id = self.id.unwrap_or_default();

        Ok(GroceryList {
            id,
            name,
            created_at: now,
        })
    }
}

// ─── GroceryItem ────────────────────────────────────────────────────────────

/// One line on a `GroceryList`.
///
/// Construction goes through [`GroceryItemBuilder`], or via
/// `plan_grocery_additions` for meal-generated lines. Direct field
/// construction is `pub` so the storage layer can reconstruct items from
/// database rows.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct GroceryItem {
    /// Globally unique, time-ordered identifier.
    pub id: GroceryItemId,
    /// Which list this item belongs to.
    pub list_id: GroceryListId,
    /// The item's name (e.g. "flour"). Must not be empty after trimming.
    pub name: String,
    /// Freetext quantity, if recorded (no unit parsing — see `meal.rs`).
    pub qty: Option<String>,
    /// Optional free-form category (e.g. "produce") for grouping in the UI.
    pub category: Option<String>,
    /// Whether the item has been checked off.
    pub checked: bool,
    /// Manual or generated from a meal.
    pub source: GrocerySource,
    /// The meal this item was generated from, if `source == FromMeal`.
    pub source_meal_id: Option<MealId>,
    /// When this item was first added to the list.
    pub created_at: OffsetDateTime,
}

/// Builder for [`GroceryItem`].
///
/// Enforces the invariants the struct requires:
/// - `name` must not be empty after trimming.
/// - `now` must be set (used for `created_at`).
///
/// Optional fields default sensibly: `checked` to `false`, `source` to
/// `Manual` (the common case — a household member typing an item in), and
/// `qty`/`category`/`source_meal_id` to `None`.
#[derive(Debug)]
pub struct GroceryItemBuilder {
    /// Which list this item belongs to.
    list_id: GroceryListId,
    /// The item's name. Required (set in `new()`); validated on `build()`.
    name: Option<String>,
    /// Freetext quantity.
    qty: Option<String>,
    /// Optional free-form category.
    category: Option<String>,
    /// Checked-off state; defaults to false (not yet bought).
    checked: bool,
    /// Manual vs generated; defaults to Manual.
    source: GrocerySource,
    /// Originating meal, if generated.
    source_meal_id: Option<MealId>,
    /// Caller-supplied id, used by the storage layer to reconstruct a row
    /// with its existing id rather than minting a fresh one.
    id: Option<GroceryItemId>,
    /// Current wall-clock time for `created_at`. Required.
    now: Option<OffsetDateTime>,
}

impl GroceryItemBuilder {
    /// Start building a new item for the given list, with the given name.
    #[must_use]
    pub fn new(list_id: GroceryListId, name: impl Into<String>) -> Self {
        Self {
            list_id,
            // Store as-is; the non-empty check happens in build().
            name: Some(name.into()),
            // No quantity unless set.
            qty: None,
            // No category unless set.
            category: None,
            // A freshly added item has not been bought yet.
            checked: false,
            // Manual is the common case — typed directly onto the list.
            source: GrocerySource::Manual,
            // No originating meal unless the source is FromMeal.
            source_meal_id: None,
            // No caller-supplied id unless the storage layer sets one.
            id: None,
            // now must be supplied for deterministic timestamps.
            now: None,
        }
    }

    /// Set the freetext quantity.
    #[must_use]
    pub fn qty(mut self, qty: impl Into<String>) -> Self {
        // Wrap in Some; None (the default) means "no quantity recorded".
        self.qty = Some(qty.into());
        self
    }

    /// Set the optional free-form category.
    #[must_use]
    pub fn category(mut self, category: impl Into<String>) -> Self {
        // Wrap in Some; None (the default) means "uncategorised".
        self.category = Some(category.into());
        self
    }

    /// Set the checked-off state (defaults to `false`).
    #[must_use]
    pub fn checked(mut self, checked: bool) -> Self {
        // Overrides the false default — used by storage reconstruction.
        self.checked = checked;
        self
    }

    /// Set the source (defaults to `Manual`).
    #[must_use]
    pub fn source(mut self, source: GrocerySource) -> Self {
        // Overrides the Manual default (e.g. FromMeal for generated items).
        self.source = source;
        self
    }

    /// Set the originating meal (relevant when `source == FromMeal`).
    #[must_use]
    pub fn source_meal_id(mut self, meal_id: MealId) -> Self {
        // Wrap in Some; None means "no originating meal" (manual items).
        self.source_meal_id = Some(meal_id);
        self
    }

    /// Supply a specific id (used by the storage layer to reconstruct a row
    /// with its existing id). Production callers creating a brand-new item
    /// should not call this — `build()` mints a fresh id when absent.
    #[must_use]
    pub fn id(mut self, id: GroceryItemId) -> Self {
        self.id = Some(id);
        self
    }

    /// Supply the current wall-clock time for `created_at` (required).
    #[must_use]
    pub fn now(mut self, now: OffsetDateTime) -> Self {
        self.now = Some(now);
        self
    }

    /// Validate all invariants and construct the `GroceryItem`.
    ///
    /// # Errors
    ///
    /// Returns [`GroceryError::EmptyName`] if the name is blank.
    /// Returns [`GroceryError::MissingNow`] if `now` was not set.
    pub fn build(self) -> Result<GroceryItem, GroceryError> {
        // Name is set unconditionally in new(); validate its trimmed form.
        let name = self.name.unwrap_or_default();
        if name.trim().is_empty() {
            return Err(GroceryError::EmptyName);
        }

        // now is required for a complete GroceryItem.
        let now = self.now.ok_or(GroceryError::MissingNow)?;

        // Use the caller-supplied id (storage reconstruction) or mint a
        // fresh time-ordered one (new-item construction).
        let id = self.id.unwrap_or_default();

        Ok(GroceryItem {
            id,
            list_id: self.list_id,
            name,
            qty: self.qty,
            category: self.category,
            checked: self.checked,
            source: self.source,
            source_meal_id: self.source_meal_id,
            created_at: now,
        })
    }
}

// ─── GroceryError ───────────────────────────────────────────────────────────

/// Errors produced when building or parsing grocery-related types.
#[derive(Debug, thiserror::Error)]
pub enum GroceryError {
    /// `name` was absent or contained only whitespace.
    #[error("grocery name must not be empty")]
    EmptyName,

    /// `now` was not set on the builder.
    #[error("required field not set: now")]
    MissingNow,

    /// The database contained an unrecognised `source` string.
    #[error("unknown grocery source: {0}")]
    UnknownSource(String),
}

// ─── plan_grocery_additions ─────────────────────────────────────────────────

/// Normalise a name for case-insensitive, trim-insensitive comparison.
///
/// Centralised so pantry-matching, already-present-matching, and within-run
/// dedupe all agree on what counts as "the same ingredient". Comparison is
/// by name only — no unit parsing, no arithmetic (see `meal.rs`).
fn normalise(name: &str) -> String {
    // Trim first so " Flour " and "flour" compare equal, then lowercase so
    // "Flour" and "flour" do too.
    name.trim().to_lowercase()
}

/// Compute which `GroceryItem`s should be added to `list_id` from `meals`.
///
/// This is the heart of P2 Slice 1's grocery generation. It is pure and
/// clock-injected: given the same inputs and `now`, it always produces the
/// same additions, and it never touches `existing` or `pantry`.
///
/// # Behaviour
///
/// 1. Every `IngredientLine` from every meal in `meals` is a candidate.
///    Callers are expected to have already filtered `meals` to the desired
///    date range — this function does **not** filter by date.
/// 2. A candidate is **dropped** if its name matches (case-insensitive,
///    trimmed) any `PantryItem.name` in `pantry` — pantry staples are never
///    suggested.
/// 3. A candidate is **dropped** if its name matches (case-insensitive,
///    trimmed) any `GroceryItem.name` already in `existing` — this is the
///    no-clobber invariant: a checked, manual, or otherwise already-present
///    item is left exactly as it is; this function only ever returns
///    additions, never mutations.
/// 4. Candidates are **deduped** among themselves by name (case-insensitive,
///    trimmed): if two meals both list "milk", only one addition is produced,
///    carrying the `qty` from the first occurrence encountered (`meals`
///    order, then each meal's `ingredient_lines` order) and attributed
///    (`source_meal_id`) to that first meal.
/// 5. Each surviving candidate becomes a `GroceryItem` with `source:
///    GrocerySource::FromMeal`, `checked: false`, `category: None`, and the
///    given `now` as its `created_at`.
///
/// The returned `Vec` contains **only** the new additions — `existing` is
/// taken by shared reference and is never mutated, removed from, or echoed
/// back; the caller is responsible for persisting the additions alongside
/// the untouched existing rows.
#[must_use]
pub fn plan_grocery_additions(
    meals: &[Meal],
    pantry: &[PantryItem],
    existing: &[GroceryItem],
    list_id: GroceryListId,
    now: OffsetDateTime,
) -> Vec<GroceryItem> {
    // Pre-normalise the pantry and existing-list names once, up front, so
    // the per-line matching below is a cheap set lookup rather than a
    // repeated scan-and-normalise over both slices for every ingredient line.
    let pantry_names: std::collections::HashSet<String> =
        pantry.iter().map(|p| normalise(&p.name)).collect();
    let existing_names: std::collections::HashSet<String> =
        existing.iter().map(|e| normalise(&e.name)).collect();

    // Tracks which normalised names have already produced an addition in
    // this run, so a second meal listing "milk" does not add it twice.
    let mut seen_in_additions: std::collections::HashSet<String> = std::collections::HashSet::new();

    // Accumulates the resulting GroceryItems in encounter order.
    let mut additions = Vec::new();

    // Walk meals, then each meal's ingredient lines, in order — this order
    // is what "first occurrence" means for both dedupe and attribution.
    for meal in meals {
        for line in &meal.ingredient_lines {
            let key = normalise(&line.name);

            // Skip pantry staples, already-present list items, and anything
            // already added earlier in this same run.
            if pantry_names.contains(&key)
                || existing_names.contains(&key)
                || seen_in_additions.contains(&key)
            {
                continue;
            }

            // Mark this name as handled so a later duplicate (from another
            // meal) is skipped by the check above.
            seen_in_additions.insert(key);

            // Build the addition via the builder so it goes through the
            // same validation as any other GroceryItem. The name is known
            // non-empty here in practice (an ingredient line with a blank
            // name would already be a data-entry bug upstream), but if it
            // ever were empty the builder's EmptyName rejection would apply
            // — build() is infallible in the paths this function exercises,
            // so unwrap_or-style silent dropping is avoided; a malformed
            // line is either upstream's bug or bypasses normal construction
            // entirely, and either way surfacing loudly is preferable.
            let item = GroceryItemBuilder::new(list_id, line.name.clone())
                .source(GrocerySource::FromMeal)
                .source_meal_id(meal.id)
                .now(now);

            // qty is freetext; carry it over verbatim when present.
            let item = if let Some(qty) = &line.qty {
                item.qty(qty.clone())
            } else {
                item
            };

            if let Ok(built) = item.build() {
                additions.push(built);
            }
            // An Err here means line.name was blank after all — silently
            // skipped rather than panicking, since this is pure domain code
            // with no channel to report a warning; a blank ingredient name
            // is a caller-side data problem, not this function's to solve.
        }
    }

    additions
}

// ─── Tests ──────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::meal::MealBuilder;
    use crate::pantry::PantryItemBuilder;
    use time::macros::{date, datetime};

    /// Fixed "now" for deterministic tests.
    fn fixed_now() -> OffsetDateTime {
        datetime!(2026-08-22 10:00:00 UTC)
    }

    fn list_id() -> GroceryListId {
        GroceryListId::new()
    }

    fn meal_with(name: &str, ingredients: &[(&str, Option<&str>)]) -> Meal {
        let mut builder = MealBuilder::new(name)
            .date(date!(2026 - 08 - 24))
            .now(fixed_now());
        for (ingredient_name, qty) in ingredients {
            builder = builder.ingredient(*ingredient_name, qty.map(str::to_owned));
        }
        builder.build().unwrap()
    }

    #[test]
    fn build_minimal_grocery_list() {
        let list = GroceryListBuilder::new("Groceries")
            .now(fixed_now())
            .build()
            .expect("minimal list must be valid");
        assert_eq!(list.name, "Groceries");
        assert_eq!(list.created_at, fixed_now());
    }

    #[test]
    fn empty_list_name_is_rejected() {
        let result = GroceryListBuilder::new("   ").now(fixed_now()).build();
        assert!(matches!(result, Err(GroceryError::EmptyName)));
    }

    #[test]
    fn list_missing_now_is_rejected() {
        let result = GroceryListBuilder::new("Groceries").build();
        assert!(matches!(result, Err(GroceryError::MissingNow)));
    }

    #[test]
    fn build_minimal_grocery_item() {
        let item = GroceryItemBuilder::new(list_id(), "Eggs")
            .now(fixed_now())
            .build()
            .expect("minimal item must be valid");
        assert_eq!(item.name, "Eggs");
        assert!(!item.checked);
        assert_eq!(item.source, GrocerySource::Manual);
        assert!(item.source_meal_id.is_none());
        assert!(item.qty.is_none());
        assert!(item.category.is_none());
    }

    #[test]
    fn empty_item_name_is_rejected() {
        let result = GroceryItemBuilder::new(list_id(), "   ")
            .now(fixed_now())
            .build();
        assert!(matches!(result, Err(GroceryError::EmptyName)));
    }

    #[test]
    fn item_missing_now_is_rejected() {
        let result = GroceryItemBuilder::new(list_id(), "Eggs").build();
        assert!(matches!(result, Err(GroceryError::MissingNow)));
    }

    #[test]
    fn grocery_source_round_trips_through_string() {
        for source in [GrocerySource::Manual, GrocerySource::FromMeal] {
            let s = source.to_string();
            let parsed: GrocerySource = s.parse().expect("known source string");
            assert_eq!(source, parsed, "round-trip failed for {source}");
        }
    }

    #[test]
    fn unknown_source_returns_error() {
        let result: Result<GrocerySource, _> = "bogus".parse();
        assert!(matches!(result, Err(GroceryError::UnknownSource(_))));
    }

    // ─── plan_grocery_additions properties ──────────────────────────────

    #[test]
    fn happy_path_generates_one_item_per_line() {
        // One meal, 3 lines, empty pantry + empty list -> 3 additions, all
        // FromMeal / unchecked / attributed to the meal.
        let meal = meal_with(
            "Spaghetti",
            &[
                ("spaghetti", Some("500g")),
                ("tomato sauce", None),
                ("parmesan", Some("a block")),
            ],
        );
        let additions = plan_grocery_additions(
            std::slice::from_ref(&meal),
            &[],
            &[],
            list_id(),
            fixed_now(),
        );

        assert_eq!(additions.len(), 3);
        for item in &additions {
            assert_eq!(item.source, GrocerySource::FromMeal);
            assert!(!item.checked);
            assert_eq!(item.source_meal_id, Some(meal.id));
        }
        let names: Vec<&str> = additions.iter().map(|i| i.name.as_str()).collect();
        assert_eq!(names, vec!["spaghetti", "tomato sauce", "parmesan"]);
    }

    #[test]
    fn pantry_suppression_drops_matching_lines() {
        // A meal listing "Flour" plus a pantry item "flour" (different case)
        // must not produce a "flour" addition.
        let meal = meal_with("Bread", &[("Flour", None), ("yeast", None)]);
        let pantry = vec![
            PantryItemBuilder::new("flour")
                .now(fixed_now())
                .build()
                .unwrap(),
        ];

        let additions = plan_grocery_additions(&[meal], &pantry, &[], list_id(), fixed_now());

        let names: Vec<&str> = additions.iter().map(|i| i.name.as_str()).collect();
        assert_eq!(names, vec!["yeast"], "flour must be suppressed by pantry");
    }

    #[test]
    fn already_present_items_are_not_duplicated_or_mutated() {
        // An existing checked, manual "eggs" plus a meal listing "eggs" must
        // not produce an "eggs" addition. The function returns only
        // additions and cannot mutate `existing` (it is a shared reference).
        let meal = meal_with("Omelette", &[("eggs", Some("6")), ("chives", None)]);
        let existing_eggs = GroceryItemBuilder::new(list_id(), "eggs")
            .checked(true)
            .source(GrocerySource::Manual)
            .now(fixed_now())
            .build()
            .unwrap();
        let existing = vec![existing_eggs.clone()];

        let additions = plan_grocery_additions(&[meal], &[], &existing, list_id(), fixed_now());

        let names: Vec<&str> = additions.iter().map(|i| i.name.as_str()).collect();
        assert_eq!(
            names,
            vec!["chives"],
            "eggs must be suppressed as already-present"
        );
        // The existing item is untouched by construction: plan_grocery_additions
        // took `existing` by shared reference, so it could not have been mutated.
        assert!(existing_eggs.checked);
        assert_eq!(existing_eggs.source, GrocerySource::Manual);
    }

    #[test]
    fn within_range_duplicates_are_deduped_to_one_addition() {
        // Two meals both listing "milk" must produce exactly one addition,
        // carrying the first meal's qty and attribution.
        let meal_a = meal_with("Pancakes", &[("milk", Some("1 cup"))]);
        let meal_b = meal_with("Cereal", &[("milk", Some("2 cups"))]);

        let additions =
            plan_grocery_additions(&[meal_a.clone(), meal_b], &[], &[], list_id(), fixed_now());

        assert_eq!(additions.len(), 1);
        assert_eq!(additions[0].name, "milk");
        assert_eq!(additions[0].qty.as_deref(), Some("1 cup"));
        assert_eq!(additions[0].source_meal_id, Some(meal_a.id));
    }

    #[test]
    fn no_meals_produces_no_additions() {
        // Edge case: an empty meals slice must produce an empty result, not
        // panic or error.
        let additions = plan_grocery_additions(&[], &[], &[], list_id(), fixed_now());
        assert!(additions.is_empty());
    }
}
